// Mocks generated by Mockito 5.4.6 from annotations
// in client/test/features/user_management/data/repositories/user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:client/core/network/http_client.dart' as _i2;
import 'package:client/features/auth/data/models/user_model.dart' as _i3;
import 'package:client/features/user_management/data/datasources/user_remote_datasource.dart'
    as _i4;
import 'package:client/features/user_management/data/models/user_create_dto.dart'
    as _i6;
import 'package:client/features/user_management/data/models/user_update_dto.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHttpClient_0 extends _i1.SmartFake implements _i2.HttpClient {
  _FakeHttpClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i4.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HttpClient get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeHttpClient_0(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i2.HttpClient);

  @override
  _i5.Future<List<_i3.UserModel>> getUsers({int? skip = 0, int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {#skip: skip, #limit: limit}),
            returnValue: _i5.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
          )
          as _i5.Future<List<_i3.UserModel>>);

  @override
  _i5.Future<_i3.UserModel> getUserById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [id]),
            returnValue: _i5.Future<_i3.UserModel>.value(
              _FakeUserModel_1(this, Invocation.method(#getUserById, [id])),
            ),
          )
          as _i5.Future<_i3.UserModel>);

  @override
  _i5.Future<_i3.UserModel> createUser(_i6.UserCreateDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [dto]),
            returnValue: _i5.Future<_i3.UserModel>.value(
              _FakeUserModel_1(this, Invocation.method(#createUser, [dto])),
            ),
          )
          as _i5.Future<_i3.UserModel>);

  @override
  _i5.Future<_i3.UserModel> updateUser(String? id, _i7.UserUpdateDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [id, dto]),
            returnValue: _i5.Future<_i3.UserModel>.value(
              _FakeUserModel_1(this, Invocation.method(#updateUser, [id, dto])),
            ),
          )
          as _i5.Future<_i3.UserModel>);

  @override
  _i5.Future<void> deleteUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
